### ISSUE TITLE
"Error: Unknown command "shell"."

### ISSUE THREAD

**Issue by rishav** [svkurowski/yii2-shell#1]
I set this up as per instructions. Doesn't seem to work.

**Comment by svkurowski** [comment]
To test this, can you perform the following steps?

``` bash
cd /tmp && git clone https://github.com/yiisoft/yii2-app-basic.git && cd yii2-app-basic
composer require --dev --prefer-dist svkurowski/yii2-shell
```

At this point, you should be able to run `./yii shell` and get an error message like this:

```
PHP Strict Warning 'yii\base\ErrorException' with message 'Declaration of Psy\Shell::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output)'
```

Now add `"prefer-stable": true,` right after `"minimum-stability": "dev",` in the `composer.json` file and execute `composer update`.
Executing `./yii shell` should now drop you into the Psysh.

**Comment by rishav** [comment]
Worked. Cheers & Thanks!

**Comment by svkurowski** [comment]
Great, I'll close this issue for now.
